# Generated by Django 6.0.2 on 2026-02-28 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Analises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateTimeField(max_length=100)),
                ('coletador', models.CharField(max_length=100)),
                ('estacao', models.CharField(max_length=100)),
                ('processador_bac', models.CharField(max_length=100)),
                ('data_processamento_bac', models.DateTimeField(max_length=100)),
                ('processador_dbo', models.CharField(max_length=100)),
                ('data_incubacao_dbo', models.DateTimeField(max_length=100)),
                ('lote', models.CharField(max_length=100)),
                ('controle', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True, max_length=500, null=True)),
                ('resultado', models.CharField(max_length=100)),
                ('data_resultado', models.DateTimeField(max_length=100)),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analises.origem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analises.usuario')),
            ],
        ),
    ]
