# Generated by Django 6.0.2 on 2026-02-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0003_parametro_delete_parametros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analises',
            name='data_coleta',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='analises',
            name='data_incubacao_dbo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='analises',
            name='data_processamento_bac',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='analises',
            name='data_resultado',
            field=models.DateTimeField(),
        ),
    ]
