# Generated by Django 6.0.2 on 2026-02-28 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0004_alter_analises_data_coleta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='analises',
            name='data_resultado',
        ),
        migrations.RemoveField(
            model_name='analises',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='analises',
            name='usuario',
        ),
        migrations.AddField(
            model_name='analises',
            name='amostra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analises',
            name='data_incubacao_dbo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analises',
            name='data_processamento_bac',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnaliseParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('data_hora_resultado', models.DateTimeField(blank=True, null=True)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_parametros', to='analises.analises')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analises.parametro')),
                ('analista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analises.analista')),
            ],
        ),
        migrations.AlterField(
            model_name='analises',
            name='coletador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas_realizadas', to='analises.analista'),
        ),
        migrations.AlterField(
            model_name='analises',
            name='processador_bac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processamentos_bac', to='analises.analista'),
        ),
        migrations.AlterField(
            model_name='analises',
            name='processador_dbo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processamentos_dbo', to='analises.analista'),
        ),
    ]
