# Generated by Django 6.0.2 on 2026-02-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0005_analista_remove_analises_data_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analises',
            name='processador_bac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analises',
            name='processador_dbo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
