# Generated by Django 6.0.2 on 2026-03-01 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0006_alter_analises_processador_bac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analises',
            name='hora_coleta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analises',
            name='hora_incubacao_dbo',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analises',
            name='hora_processamento_bac',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analiseparametro',
            name='analise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analises.analises'),
        ),
        migrations.AlterField(
            model_name='analiseparametro',
            name='analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analises.analista'),
        ),
        migrations.AlterField(
            model_name='analises',
            name='data_coleta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analises',
            name='data_incubacao_dbo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analises',
            name='data_processamento_bac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
